### ISSUE TITLE
[FR] Cutting Filament Sequence

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/MM-control-01#137]
I would like to request filament cut/trim sequence as this may be helpful. I personally haven't been printing in mmu for quite a time now and that time my problem mostly because of the blobs that is larger than the teflon tube. The selector has a blade integrated but never been fully utilized to automatically trim the filament though I do remember Prusa himself said will trim the filament end last year form an interview video.

What I have in mind is to move the selector +1 from the current filament slot. For example I want to trim f2, I move the selector to f3 first, extrude a bit of f2. From this point out, it is either leave the f2 filament there as selector goes f3-f5 or goes back to f2 to trim the filament. If changing from f2 to f1, same sequence has to occur, first which moves the selector to f3 at least, then going to f1, the f2 filament will be trimmed.

This may solve most of the filament transition problem during printing

**Comment by mkbel** [comment]
Filament cutting is already implemented in MMU firmware, but the feature is not yet enabled in printer firmware, as it is not sufficiently tested. You can build https://github.com/prusa3d/Prusa-Firmware/ yourself, just uncomment line //#define MMU_HAS_CUTTER in Prusa-Firmware/Firmware/variants/your_printer_variant.h e.g.: https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/variants/1_75mm_MK3S-EINSy10a-E3Dv6full.h. You will have two new menu items in your printer firmware - cut filament and enable cutter. The first one is to initiate filament cut manually to test the feature. The second one enables cutting filament automatically, after loading the filament to the nozzle failed.
