### ISSUE TITLE
Ask filament at the very start of single prints

### ISSUE THREAD

**Issue by murphy2712** [prusa3d/MM-control-01#36]
When printing in single mode, the printer heats up (1-2 minutes), then moves to X0 Y0 Z0.2 and only then asks for which filament to use.
It would be much more convenient to ask which filament to use at the very beginning of the print (right after selecting the file on sdcard).
This happened to me several times that I start the print and forgot to come back selecting the filament. Last time the printer stayed the whole night with the hotend touching the PEI sheet at 240 asking for the filament... This isn't good for the PEI sheet!
The hotend should also timeout and cooldown when no filament is selected after x minutes. I don't want it to start a fire!

**Comment by mkbel** [comment]
It is already planed to be fixed.
