### ISSUE TITLE
Independent MMU control

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/MM-control-01#38]
It would be great if you could load the machine with the MMU, then put it in 'bypass' mode.

Typically you can just reach in the back and rotate the selector drum to where it doesn't drag, but it would be nice to run my old, non-MMU aware sliced g-code.

Right now you can select filament, and pre-load it ('prime the mmu'?) - but you can't get it to the nozzle.

**Comment by mkbel** [comment]
This feature is planned. http://dev.prusa3d.com/browse/PFW-555
