### ISSUE TITLE
Missing Beep, when MMU needs user attention

### ISSUE THREAD

**Issue by KarlZeilhofer** [prusa3d/MM-control-01#46]
In my case, the filament got stuck in the extruder bowden hose, and the filament got ground to the half diameter in the MMU. It reseted in that situation for at least one hour, even though I was in the room nearby, but didn't notice the problem.

**Comment by Sylvian** [comment]
Same here ^^ implementation will be usefull

**Comment by AbeFM** [comment]
Oooo! Ignore me too! I also think this!

**Comment by 0versizedHat** [comment]
Seriously how is this still an open issue?

**Comment by JohnnyDeer** [comment]
This feature is already implemented in FW, I´m closing.
