### ISSUE TITLE
Calibrating Tube Length, Materials

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/MM-control-01#59]
Calibrating the tube length depends on what you're feeding. I can get PLA or PETg to feed and always end up within 1-2 mm on the hobbed gear, but feeding TPU will fall well short (not visible, about 1.5cm short).

I feel that when the printer is printing with a TPU, and knows it, it compensates? I certainly was BARELY getting anything out of the printer, the entire purge was extruding air, then it would pick up as I got to the object.

What I'm wondering is if I need to recalibrate all 5 channels every time I change filament material. If so, it speaks to having a multiplicative constant for each channel, then setting one overall would scale the rest?

**Comment by KarlZeilhofer** [comment]
Just like I said. :smile: 

The interface to the printer has something defined to tell the MMU2 the material to be printed. But currently the firmware of MMU2 ignores such values.

**Comment by clearbucketLabs** [comment]
usually compression of the filament changes the effective gear ratio making the steps per mm slightly different per type of filament, usually it isn't too much but over x length it would get more pronounced...

**Comment by AbeFM** [comment]
A small percentage difference is a big change over the length of the bowden tube - my gears having a tenth of a mm difference was a cm of travel.

The whole feeding of the printer by the MMU is handled pretty badly. Ignored sensors, wrong speeds, wrong lengths, mismatched timings.

It's generally better than standing there yourself.

**Comment by FaultyLine** [comment]
I'm having an issue where no matter the tube length calibration I do, the MMU2 pulley forces too much filament into the extruder. I made a mechanical buffer for the filament on the selector that's working pretty great. 

https://www.youtube.com/watch?v=W3ctB_X0odY

**Comment by AbeFM** [comment]
Set gear to nozzle distance, extra unload, etc till you get it right. If
the extruder or firmware isn't stock (neither of mine are) you'll need to
make sure they are all set correctly to avoid grinding.

                  Thanks!
                          -Abe.

**Comment by FaultyLine** [comment]
It's Prusa firmware - I haven't customized anything and have followed the calibration routine over and over again. I basically gave up on making it work the way it's supposed to and am just waiting for the MMU2S upgrade, which adds the extruder sensor so I don't have to deal with this anymore.

**Comment by JohnnyDeer** [comment]
This problematic is solved by MMU2S, I´m closing.
