### ISSUE TITLE
 On MMU-Single prints, ask user for material as soon as print is started.

### ISSUE THREAD

**Issue by AbeFM** [prusa3d/MM-control-01#64]
https://github.com/prusa3d/Slic3r/issues/1333

https://github.com/prusa3d/Prusa-Firmware/issues/1265

I'm not sure what it takes to get SOMEONE at prusa to say "Yes, we're willing to talk about this"... But it seems like if people don't post something 12 times in 15 places, it gets ignored.

This makes more reading for the devs than if you just answered the posts. WE as users don't know what you're working on, all we see is our notifying the development team there are issues and we get nothing but put off. If the issue is "being considered by the firmware team" why isn't there an open issue for it?

Quoting:
Slicer Ver:
1.41.1

Operating system type + version
Win10x64/NA

Behavior
Slice a print using MMU Single compatible printer. Initiate print.
Printer preheats, mesh levels, moves back to home and then asks you for the material.

I have had this lead to my coming back 16 hours later with the bed cooking at 85 degrees and nothing has happened. Many, many many times I've forgotten for a shorter period of time, and in general it means sitting in front of the printer watching it do nothing for 5-10 extra minutes per print.

It would be great if the slicer and/or printer could conspire to ask you which channel you want to use as soon as you select the file.

Not to double up, but I would also like to be able to set the channel in the slicing/on the PC

Is this a new feature request?
Yes?

**Comment by mkbel** [comment]
This feature has been implemented. https://github.com/prusa3d/Prusa-Firmware/pull/1290

**Comment by johnbiggs** [comment]
If this is fixed, why did my Mk2.5 MMU2 on v3.5 literally cook for 4 hours? Because I walked away when I heard the bed leveling start.
