### ISSUE TITLE
LICENSE: What is the license for this code?

### ISSUE THREAD

**Issue by alexxy** [prusa3d/MM-control-01#71]
Hi!

Subj...

**Comment by KarlZeilhofer** [comment]
Should be GPL, but I also was missing that info anywhere.

**Comment by mylife4aiurr** [comment]
I thought all code posted for all to see on github was open source?? Thought that was the purpose of having all code for others to see and download and modify and then share again??

**Comment by KarlZeilhofer** [comment]
Open source just means, that you publish your code. But further more it is essential, what others are allowed to do with the code. If you own the copy right (you are the author), then you may or may not allow others to copy/modify/reuse/republish your code.

**Comment by mkbel** [comment]
License specified https://github.com/prusa3d/MM-control-01/pull/73
