### ISSUE TITLE
Disengage the selector when booting and filament detected by FINDA

### ISSUE THREAD

**Issue by johnbiggs** [prusa3d/MM-control-01#84]
When the printer is in this condition (All lights flashing) the selector is sometimes engaged making it impossible to pull out the material or unload the extruder. Rotate the selector to a disengaged state when booting and filament is detected OR allow the buttons to rotate the selector even if position is unknown.

**Comment by PavelSindler** [comment]
Since 1.0.3-RC1 fw there is possibility to unload filament and even start new print if filament is loaded in nozzle on mmu boot.

**Comment by JohnnyDeer** [comment]
This problematic is solved on new fw versions, I´m closing.
